using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AventStack.ExtentReports;
using IntuneCanaryTests.Models;
using IntuneCanaryTests.Utilities;

namespace IntuneCanaryTests
{
    /// <summary>
    /// Rerun Failed Tests - Executes only tests that failed in previous run
    /// Uses TestData/FailedTests_Rerun.json generated by Extract-FailedTests.ps1
    /// </summary>
    [TestFixture]
    [Parallelizable(ParallelScope.Self)]
    public class DataDrivenTests_FailedRerun : SecurityBaseline
    {
        protected ExtentTest? _test;

        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            // Kill any orphaned browser processes before starting
            CleanupBrowserProcesses();
            
            // Configure Playwright browser launch args for resource optimization
            Environment.SetEnvironmentVariable("PLAYWRIGHT_CHROMIUM_ARGS", 
                "--disable-dev-shm-usage --disable-gpu --no-sandbox --disable-setuid-sandbox --disable-web-security --disable-features=IsolateOrigins,site-per-process --js-flags=--max-old-space-size=512");
        }

        private void CleanupBrowserProcesses()
        {
            try
            {
                var processes = System.Diagnostics.Process.GetProcesses()
                    .Where(p => p.ProcessName.Contains("chrome", StringComparison.OrdinalIgnoreCase) ||
                               p.ProcessName.Contains("msedge", StringComparison.OrdinalIgnoreCase) ||
                               p.ProcessName.Contains("playwright", StringComparison.OrdinalIgnoreCase));
                
                foreach (var process in processes)
                {
                    try
                    {
                        process.Kill(true);
                        process.WaitForExit(5000);
                    }
                    catch { /* Ignore if process already exited */ }
                }
                
                Console.WriteLine("Cleaned up orphaned browser processes");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Browser cleanup warning: {ex.Message}");
            }
        }

        public override BrowserNewContextOptions ContextOptions()
        {
            var certPath = Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "..", "auth-cert", "AIAutoPE_3.pfx"));
            
            return new BrowserNewContextOptions
            {
                ViewportSize = ViewportSize.NoViewport,
                IgnoreHTTPSErrors = true,
                ClientCertificates = new[]
                {
                    new ClientCertificate
                    {
                        Origin = "https://certauth.login.microsoftonline.com/c0219094-a70e-402c-8dd2-fd89f7d64010/certauth",
                        PfxPath = certPath,
                        Passphrase = "Admin@123"
                    }
                }
            };
        }

        [SetUp]
        public void TestSetup()
        {
            Console.WriteLine($"Test Data - Failed Tests Rerun: {TestDataLoader.GetDataSummary()}");
            
            // Set Playwright timeout to 120 seconds for Login and CreateNewProfile operations
            if (Page != null)
            {
                Page.SetDefaultTimeout(120000);
                Page.SetDefaultNavigationTimeout(120000);
            }
        }

        public static IEnumerable<string> GetFailedTestCases()
        {
            var failedData = TestDataLoader.GetFailedTestsData();
            return failedData.TestCases
                .Where(tc => tc.Enabled)
                .Select(tc => tc.TestCaseId);
        }

        [Test]
        [TestCaseSource(nameof(GetFailedTestCases))]
        public async Task RerunFailedTest(string testCaseId)
        {
            var testData = TestDataLoader.GetFailedTestsData()
                .TestCases.FirstOrDefault(t => t.TestCaseId == testCaseId);

            Assert.That(testData, Is.Not.Null, $"Test case {testCaseId} not found in FailedTests_Rerun.json");

            Console.WriteLine($"\n═══════════════════════════════════════════════════════════════");
            Console.WriteLine($"  RERUNNING FAILED TEST: {testData!.TestCaseId}");
            Console.WriteLine($"═══════════════════════════════════════════════════════════════\n");
            Console.WriteLine($"Test Case: {testData.TestName}");
            Console.WriteLine($"Description: {testData.Description}");
            Console.WriteLine($"Priority: {testData.Priority}\n");

            _test = TestInitialize.CreateTest($"[RERUN] {testData.TestCaseId}: {testData.TestName}", testData.Description);
            _test.AssignCategory("Failed-Rerun");
            _test.AssignCategory(testData.Category);

            try
            {
                Assert.That(Page, Is.Not.Null, "Page object is null");

                Console.WriteLine("[STEP 1] Logging into Intune Portal");
                _test.Log(Status.Info, "Starting Intune Login");
                await Login(Page);
                await Task.Delay(3000);
                _test.Log(Status.Pass, "Successfully logged into Intune Portal");

                Console.WriteLine("\n[STEP 2] Creating new security baseline profile");
                _test.Log(Status.Info, $"Creating profile: {testData.Parameters.SecBaselineName}");
                _test.Log(Status.Info, $"→ Parent Setting: {testData.Parameters.ParentDropDown} = {testData.Parameters.ParentDropDownOption}");
                if (!string.IsNullOrEmpty(testData.Parameters.ChildDropDown))
                {
                    _test.Log(Status.Info, $"→ Child Setting: {testData.Parameters.ChildDropDown} = {testData.Parameters.ChildDropDownOption}");
                }
                
                var p = testData.Parameters;
                await CreateNewProfile(
                    Page,
                    p.FirstLink,
                    p.SecondLink,
                    p.SecBaselineName,
                    p.ConfigurationSettings,
                    p.ParentDropDown,
                    p.ParentDropDownOption,
                    p.ChildDropDown,
                    p.ChildDropDownOption,
                    p.ParentSectionPath,
                    p.ChildSectionPath
                );

                var screenshotPath = await ExtentReportHelper.CaptureScreenshot(Page, $"{testData.TestCaseId}_Rerun_Success");
                if (!string.IsNullOrEmpty(screenshotPath))
                {
                    _test.Log(Status.Pass, "✅ TEST PASSED ON RERUN: Profile created successfully", 
                        MediaEntityBuilder.CreateScreenCaptureFromPath(screenshotPath).Build());
                }

                Console.WriteLine($"\n✅ RERUN PASSED: {testData.TestCaseId} executed successfully");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"\n❌ RERUN STILL FAILED: {ex.Message}");
                Console.WriteLine($"Stack Trace: {ex.StackTrace}");

                _test.Log(Status.Fail, $"❌ Test Failed on Rerun: {ex.Message}");

                try
                {
                    var screenshotPath = await ExtentReportHelper.CaptureScreenshot(Page, $"{testData.TestCaseId}_Rerun_Failed");
                    if (!string.IsNullOrEmpty(screenshotPath))
                    {
                        _test.AddScreenCaptureFromPath(screenshotPath);
                    }
                }
                catch (Exception screenshotEx)
                {
                    Console.WriteLine($"Failed to capture screenshot: {screenshotEx.Message}");
                    _test.Log(Status.Warning, $"Could not capture failure screenshot: {screenshotEx.Message}");
                }

                throw;
            }
        }

        [TearDown]
        public async Task TestCleanup()
        {
            Console.WriteLine("\n[TEARDOWN] Starting test cleanup...");
            ExtentReportHelper.FlushReport();
            
            // Explicit cleanup to free browser resources
            try
            {
                if (Context != null)
                {
                    await Context.CloseAsync();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Context cleanup warning: {ex.Message}");
            }
        }

        [OneTimeTearDown]
        public void OneTimeCleanup()
        {
            // Final cleanup of any remaining browser processes
            CleanupBrowserProcesses();
        }
    }
}
